name: test_app
description: TEST Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.11

  firebase_core: ^1.12.0
  # firebase_analytics: ^7.1.1 no nullsafe... skip it for now
  firebase_auth: ^3.3.6
  firebase_dynamic_links: ^4.0.5
  firebase_storage: ^10.2.7
  firebase_messaging: ^11.2.6
  cloud_firestore: ^3.1.7

  get: ^4.1.3
  get_storage: ^2.0.2

#  sms_autofill: ^2.2.0

  country_code_picker: ^2.0.2

  google_sign_in: ^5.2.3
  # kakao_flutter_sdk: ^0.9.0  보류.. 메인 기능부터 개발

  logger: ^1.1.0
  flutter_local_notifications: ^9.3.1
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+9
  intl: ^0.17.0
  photo_view: ^0.13.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
